services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    networks:
      - network-backend
    depends_on:
      - backend

  backend:
    build: ./backend
    restart: always
    ports:
      - '3100:3100'
    networks:
      - network-backend
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql
    restart: always
    networks:
      - network-backend
    env_file:
      - './backend/.env'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - mysql_data:/data/db
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 15

networks:
  network-backend:
    driver: bridge

volumes:
  mysql_data:
